import { GitHubLogoIcon, TwitterLogoIcon } from '@radix-ui/react-icons';
import './globals.css';
import './prism.css';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const Header = () => {
  return (
    <header className='flex items-center justify-between py-8'>
      <Link href='/'>
        <div className='text-xl text-white'>Glazed UI</div>
      </Link>
      <nav className='flex gap-6'>
        <a
          href='https://twitter.com/Ibelick'
          target='_blank'
          rel='noopener noreferrer'
          className='inline-flex'
        >
          <TwitterLogoIcon className='h-6 w-6 text-slate-400 transition-colors hover:text-white' />
        </a>
        <a
          href='https://github.com/ibelick/glazed-ui'
          target='_blank'
          rel='noopener noreferrer'
          className='inline-flex'
        >
          <GitHubLogoIcon className='h-6 w-6 text-slate-400 transition-colors hover:text-white' />
        </a>
      </nav>
    </header>
  );
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='bg-black'>
          <div className='mx-auto min-h-screen max-w-5xl px-4'>
            <Header />
            <main>{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
